#include "nakano/k_math.h"

f32 TBL[4]  = { 1.0f / 3.0f, 1.0f / 5.0f,  1.0f / 7.0f,  1.0f / 9.0f };
f32 STBL[4] = { 1.0f / 6.0f, 1.0f / 20.0f, 1.0f / 42.0f, 1.0f / 72.0f };
f32 CTBL[4] = { 1.0f / 2.0f, 1.0f / 12.0f, 1.0f / 30.0f, 1.0f / 56.0f };

f32 _atan2(f32 y, f32 x) {
    __asm__ volatile(
        "mfc1        $6, %0\n"
        "beq         $0, $6, _ZEROY\n"
        "qmtc2       $6, $vf8\n"
        "mfc1        $6, %1\n"
        "beq         $0, $6, _ZEROX\n"
        "qmtc2       $6, $vf9\n"
        "vdiv        Q, $vf8x, $vf9x\n"
        "la          $6, TBL\n"
        "lqc2        $vf12, 0x0($6)\n"
        "vwaitq\n"
        "vaddq.xyzw  $vf8, $vf0, Q\n"
        "vabs.x      $vf8, $vf8\n"
        "vsubw.x     $vf9, $vf8, $vf0w\n"
        "vmax.x      $vf9, $vf9, $vf0\n"
        "qmfc2       $6, $vf9\n"
        "li          $7, 0\n"
        "beq         $0, $6, _SKIP\n"
        "vaddw.x     $vf9, $vf8, $vf0w\n"
        "vsub.x      $vf10, $vf0, $vf8\n"
        "vaddw.x     $vf10, $vf10, $vf0w\n"
        "vdiv        Q, $vf10x, $vf9x\n"
        "li.s        $6, 0.785398\n"
        "qmtc2       $6, $vf7\n"
        "li          $7, 1\n"
        "vwaitq\n"
        "vaddq.x     $vf8, $vf0, Q\n"
        "b           _SKIP\n"
    "_SKIP:\n"
        "vmove.x     $vf9, $vf8\n"
        "vmove.x     $vf10, $vf8\n"
        "vmul.x      $vf8, $vf8, $vf8\n"
        "vsub.x      $vf8, $vf0, $vf8\n"
        "vmul.x      $vf10, $vf10, $vf8\n"
        "vmulx.x     $vf11, $vf10, $vf12x\n"
        "vadd.x      $vf9, $vf9, $vf11\n"
        "vmul.x      $vf10, $vf10, $vf8\n"
        "vmuly.x     $vf11, $vf10, $vf12y\n"
        "vadd.x      $vf9, $vf9, $vf11\n"
        "vmul.x      $vf10, $vf10, $vf8\n"
        "vmulz.x     $vf11, $vf10, $vf12z\n"
        "vadd.x      $vf9, $vf9, $vf11\n"
        "vmul.x      $vf10, $vf10, $vf8\n"
        "vmulw.x     $vf11, $vf10, $vf12w\n"
        "vadd.x      $vf9, $vf9, $vf11\n"
        "beq         $0, $7, _ANS\n"
        "vsub.x      $vf9, $vf7, $vf9\n"
        "b           _ANS\n"
    "_ZEROX:\n"
        "li.s        $6, 1.57079637\n"
        "qmtc2       $6, $vf9\n"
        "b           _ANS\n"
    "_ZEROY:\n"
        "addiu       $6, $0, 0x0\n"
        "qmtc2       $6, $vf9\n"
    "_ANS:\n"
        "mfc1        $6, %1\n"
        "bgez        $6, _NEXT\n"
        "li.s        $6, 3.141592\n"
        "qmtc2       $6, $vf10\n"
        "vsub.x      $vf9, $vf10, $vf9\n"
    "_NEXT:\n"
        "mfc1        $6, %0\n"
        "bgez        $6, _NEXT2\n"
        "vsub.x      $vf9, $vf0, $vf9\n"
    "_NEXT2:\n"
        "qmfc2       $6, $vf9\n"
        "mtc1        $6, $f0\n"
    : : "f" (y), "f" (x));
}

f32 _sin(f32 rad) {
    __asm__ volatile(
        "mfc1    $6, %0\n"
        "qmtc2   $6, $vf8\n"
        "la      $6, STBL\n"
        "lqc2    $vf11, 0x0($6)\n"
        "vmove.x $vf9, $vf8\n"
        "vmul.x  $vf10, $vf8, $vf8\n"
        "vsub.x  $vf10, $vf0, $vf10\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmulx.x $vf9, $vf9, $vf11x\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmuly.x $vf9, $vf9, $vf11y\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmulz.x $vf9, $vf9, $vf11z\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmulw.x $vf9, $vf9, $vf11w\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "qmfc2   $6, $vf8\n"
        "mtc1    $6, $f0\n"
    : : "f" (rad));
}

f32 _cos(f32 rad) {
    __asm__ volatile(
        "mfc1    $6, %0\n"
        "qmtc2   $6, $vf10\n"
        "la      $6, CTBL\n"
        "lqc2    $vf11, 0x0($6)\n"
        "vaddw.x $vf8, $vf0, $vf0w\n"
        "vaddw.x $vf9, $vf0, $vf0w\n"
        "vmul.x  $vf10, $vf10, $vf10\n"
        "vsub.x  $vf10, $vf0, $vf10\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmulx.x $vf9, $vf9, $vf11x\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmuly.x $vf9, $vf9, $vf11y\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmulz.x $vf9, $vf9, $vf11z\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "vmul.x  $vf9, $vf9, $vf10\n"
        "vmulw.x $vf9, $vf9, $vf11w\n"
        "vadd.x  $vf8, $vf8, $vf9\n"
        "qmfc2   $6, $vf8\n"
        "mtc1    $6, $f0\n"
    : : "f" (rad));
}

f32 _sqrt(f32 x) {
    __asm__ volatile(
        "mfc1        $6, %0\n"
        "qmtc2       $6, $vf4\n"
        "vsqrt       Q, $vf4x\n"
        "vwaitq\n"
        "cfc2        $6, $vi22\n"
        "mtc1        $6, $f0\n"
    : : "f" (x));
}
