#include "common.h"

s32 first_enter = 0;
s32 after_puppet_dst = 0;
s32 offset_X = 0x800;
s32 offset_Y = 0x800;

// Initialize these
// DVECTOR GIMBASE_1ST_LOGO;
// DVECTOR GIMBASE_TTL_WAIT;
// DVECTOR GIMBASE_TTL_LOGO;
// DVECTOR STRBASE_OPT_SCREXPLAIN;
// DVECTOR STRBASE_OPT_CURRENT;
// DVECTOR STRBASE_OPT_PAD;
// DVECTOR STRBASE_OPT_SOUND;
// DVECTOR GIMBASE_PAD_CONTROLER;
// DVECTOR STRBASE_PAD_TYPE;
// DVECTOR STRBASE_PAD_RU;
// DVECTOR STRBASE_PAD_RD;
// DVECTOR STRBASE_PAD_RL;
// DVECTOR STRBASE_PAD_RR;
// DVECTOR STRBASE_PAD_ACTION;
// DVECTOR GIMBASE_SND_MONO;
// DVECTOR GIMBASE_SND_STEREO;
// DVECTOR GIMBASE_SND_5P1CH;
// DVECTOR STRBASE_SND_MODE;
// DVECTOR GIMBASE_ADJ_SQUARE;
// DVECTOR GIMSIZE_ADJ_SQUARE;
// DVECTOR GIMBASE_ADJ_TRIANGLE;
// DVECTOR STRBASE_ADJ_SCREXPLAIN;
// DVECTOR GIMBASE_WMP_MENU;
// DVECTOR GIMBASE_WMP_STATUS;
// DVECTOR STRBASE_WMP_PLACE;
// DVECTOR GIMBASE_GAM_PSPLACE;
// DVECTOR GIMBASE_GAM_PAUSE;
// DVECTOR GIMBASE_GAM_VISION_S;
// DVECTOR GIMBASE_GAM_START;
// DVECTOR GIMBASE_GAM_STGNAME;
// DVECTOR GIMBASE_GAM_STGINTRO;
// DVECTOR GIMBASE_GAM_VISION_O;
// DVECTOR GIMBASE_GAM_OVER;
// KZCOLOR GCOL_ADJ_SQUARE;
// KZCOLOR GCOL_ADJ_TRIANG;
// void (*kzTwoDmsnJobTbl[0])(/* parameters unknown */);
