name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCESDK: /sce

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download SDK
      run: wget -q -O sdk.tar.xz $SDK_URL
      env:
        SDK_URL: ${{secrets.SDK_URL}}
    - name: Untar SDK
      run: sudo mkdir /sce; sudo tar -xf sdk.tar.xz -C /sce; sudo ln -s /sce /usr/local/sce
    - name: Configure CMake
      run: cmake -DCMAKE_TOOLCHAIN_FILE=ps2_ee.cmake -Bbuild
    - name: Build
      run: cmake --build build
    - name: Download original ELF
      if: always()
      run: wget -q -O orig.elf $ELF_URL
      env:
        ELF_URL: ${{secrets.ELF_URL}}
    - name: Download functions.json
      if: always()
      run: wget -q -O functions.json $JSON_URL
      env:
        JSON_URL: ${{secrets.JSON_URL}}
    - name: Install diff dependencies
      if: always()
      run: pip install pyelftools rabbitizer
    - name: Run diff
      if: always()
      run: python tools/build_diff.py orig.elf build/CMakeFiles/kl2_lv_decomp.dir --json functions.json
        
  
