name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCESDK: /sce

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download SDK
      run: wget -q -O sdk.tar.xz $SDK_URL
      env:
        SDK_URL: ${{secrets.SDK_URL}}
    - name: Untar SDK
      run: sudo mkdir /sce; sudo tar -xf sdk.tar.xz -C /sce; sudo ln -s /sce /usr/local/sce
    - name: Configure CMake
      run: cmake -DCMAKE_TOOLCHAIN_FILE=cmake/ps2_ee.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DKL2_RETAIL=ON -Bbuild
    - name: Print compile_commands.json
      run: cat build/compile_commands.json
    - name: Build
      run: cmake --build build; exit 0
    - name: Download original ELF
      if: always()
      run: wget -q -O orig.elf $ELF_URL
      env:
        ELF_URL: ${{secrets.ELF_URL}}
    - name: Install cabbiter dependencies
      if: always()
      run: pip install pyelftools rabbitizer colorama
    - name: Run cabbiter
      if: always()
      run: python tools/cabbiter.py --target orig.elf --cmake build
      env:
        PARUU_API_URL: ${{secrets.PARUU_API_URL}}
        PARUU_TOKEN: ${{secrets.PARUU_TOKEN}}
        
  
